### ISSUE TITLE
(publish) Add digest to AdditionalImages/helm images pulled by tag

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#109]
To facilitate the internet-connected experience, all images uploaded to the internet-disconnected registry during publishing should have ICSP mappings. 

```
level=warning msg=no digest mapping available for registry.redhat.io/ubi8/ubi:latest, skip writing to ImageContentSourcePolicy
```

**Comment by jpower432** [comment]
@afflom Should be closed by #105
