### ISSUE TITLE
publish: write OCP release image signature config map

### ISSUE THREAD

**Issue by estroz** [openshift/oc-mirror#125]
A release signature configmap is typically created [manually](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.8/html/updating_clusters/updating-restricted-network-cluster#update-oc-configmap-signature-verification_updating-restricted-network-cluster). `publish` should handle creating this manifest alongside ICSP's and catalogsources.

**Comment by jpower432** [comment]
> Note: Another Kubernetes resource that will have to be created to make this work is called `Cincinnati`.

Putting this into a separate issue
