### ISSUE TITLE
Command errors on usage.md

### ISSUE THREAD

**Issue by SDBrett** [openshift/oc-mirror#180]
[docs/usage](https://github.com/openshift/oc-mirror/blob/main/docs/usage.md) has example commands using the command `oc-bundle` should this be replaced with `oc-mirror`?

A minor nitpick on the same page, would it be better to use the generic pull secret link `https://console.redhat.com/openshift/install/pull-secret` instead of `https://console.redhat.com/openshift/install/aws/installer-provisioned`?

**Comment by jpower432** [comment]
@SDBrett Thanks for submitting this issue! You are correct, this doc is out of date. We will get to work on updating it.
