### ISSUE TITLE
Do not re-download images

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#191]
# Version
alpha3

# What happened?

Previously downloaded releases are re-downloaded

# What you expected to happen?

If a release has previously been downloaded, it should be skipped. 

# How to reproduce it (as minimally and precisely as possible)?

Perform differential operations with a specific OCP release or latest, That version will be re-downloaded. 

# Anything else we need to know?

Redownloading blobs cant be avoided at this time, but we can control entire images and/or releases.

**Comment by jpower432** [comment]
Should be resolve in #186
