### ISSUE TITLE
Pull Secret Validation

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#196]
# Version

alpha3

# What happened?

app does not perform pull secret validation prior to beginning mirroring operations

# What you expected to happen?

Pull secrets should be validated prior to beginning mirroring operations

**Comment by SDBrett** [comment]
What sort of validation should be performed? ie Syntax or attempting to auth?

**Comment by jpower432** [comment]
> What sort of validation should be performed? ie Syntax or attempting to auth?

I think it would be both. The OCP installer has validation for pull secret syntax that we already have imported so I think we are covered there.
