### ISSUE TITLE
[RFE] Client configuration file 

### ISSUE THREAD

**Issue by SDBrett** [openshift/oc-mirror#197]
A client configuration file would be helpful to specify parameters such as the pull secret location #78, registry cert trust #91 and kubeconfig file location.

Using a client config file can make running oc-mirror easier and also provides version control ability if required.

**Comment by afflom** [comment]
I hadn't considered this approach. What do you see as the advantage(s) of this over using env vars or the existing config to pass these settings to the client?

**Comment by SDBrett** [comment]
A config file separates client specific settings to the imageset so the same imageset can be used on multiple clients.

Relying solely environmental variables assumes that the user knows all the environment variables used by `oc-mirror` (Which I don't think are referenced in documentation) and allows using paths outside of environmental vars.
