### ISSUE TITLE
fully disconnected does not respect the repository provided when there are several sub directories under the top level repository

### ISSUE THREAD

**Issue by cadjai** [openshift/oc-mirror#213]
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
I mirrored a set of operators using `oc-mirror --skip-missing --config operator-imageset-config.yaml file:///data/registry-oc-mirror` which created a bundle that I took to the disconnected side.
Once there I proceeded to upload the images to the repository we have access to which is not the root of the registry. So I used the following command to achieve that `oc-mirror --from /data/registry-oc-mirror/mirror_seq1_000000.tar docker://<registry-name>/repository-path/ `
Note that in this case repostory-path looked like top level repository with two level sub directories and the images are expected to be pushed to the lowest level of the repository not the top level.
Enter text here.
Attach the relevant portions of your `.openshift_bundle.log`.

# What you expected to happen?
The operators images should have been loaded to the path provided above which contained multiple subpath but the images didn't go to the expected location. 
Enter text here.

# How to reproduce it (as minimally and precisely as possible)?
Once you have a bundle ready to be uploaded to a registry use the `oc-mirror --from` command and provide the path to the bundle along with the repository where the image should be pushed into. Note that this has to be a sub directory or repository under the registry not the root of the registry. It appears that the command works for the root of the registry or the first sub path but does not traverse the top level repository.
At several customers where enterprise registries are used (here we are testing against artifactory) users have access to sub repository under the registry and this need to be able to handle that. If the path was provided to the oc image mirror command the images would have been pushed to the appropriate sub repositories.

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by afflom** [comment]
Thanks, @cadjai for testing! This functionality was recently added here https://github.com/openshift/oc-mirror/pull/203. You'll have to build from that commit or main for the user defined namespace to be respected. Please let us know if that PR did not solve this issue.

**Comment by afflom** [comment]
@cadjai Can you confirm that this was resolved on main?

**Comment by cadjai** [comment]
Sorry Alex - 
I tried it and got a different error, which  I suspect is related to the CA chain. For some reason the oc-mirror didn't see that the CA for the registry was already trusted. 
I got distracted and didn't pursue it further. I will try to look at it again when I get back home this weekend.

**Comment by cadjai** [comment]
I reran the push using o`c-mirror --from /data/registry-oc-mirror/mirror_seq1_000000.tar docker://<registry-fqdn>/<repository> --log-level=debug` and I get the following error `error: error checking push permissions for registry-fqdn: POST https://<registry-fqdn>/v2/oc-mirror/blobs/uploads/:  UNAUTHORIZED: User is unauthorized to upload to docker-proj-local/oc-mirror/_uploads; map[]`
Note that the destination registry is artifactory. 
Also is there a way to tell the binary which HTTP method to use? For instance I know that they registry didn't allow us to use POST to post binaries to it. So we were only allowed to use PUT. 
I am wondering if we are running into similar issue here.

**Comment by afflom** [comment]
@cadjai what commit did you build oc-mirror from?

**Comment by cadjai** [comment]
I built from latest and check that the ns commit #203 you referenced was included.

**Comment by afflom** [comment]
@cadjai is this still an issue?
