### ISSUE TITLE
[BUG] oc-mirror should support podman credentials location for registry authentication

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#216]
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?

I used `podman login` to set up my registry credentials and `oc-mirror` does not look in the location where those are saved.

# What you expected to happen?

`oc-mirror` checks `${XDG_RUNTIME_DIR}/containers/auth.json` for registry credentials

# How to reproduce it (as minimally and precisely as possible)?

Set up a test registry protected by basic auth
```console
$ podman login localhost:5000
$ oc-mirror --from mirror_seq1_000000.tar docker://localhost:5000
```

# Anything else we need to know?

This is marked as an RFE because the docs explicitly say to use `~.docker/config.json` and using this location to store registry credentials works.

The podman location is not checked because two upstream libraries use a registry client that does not check this location.
- `go-containerregsitry authn.DefaultKeychain` includes this in the main branch and will in the next release
- `operator-registry` uses a docker config library that hard codes the name of the auth file to `config.json`. Only the directory of that file can be configured.

# References

**Comment by afflom** [comment]
This is a limitation of operator-registry. We will try to address this by tech preview, but fair warning: this might not be resolved and `~/.docker/config.json` may be required until GA.

**Comment by afflom** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2028767
