### ISSUE TITLE
Can’t decode the storageConfig with local

### ISSUE THREAD

**Issue by zhouying7780** [openshift/oc-mirror#227]
# Version

```console
oc-mirror version 
v0.1.0-alpha.3

<your output here>
```

# What happened?
With backend for local config like:
[root@localhost backend]# cat imagesetbackendlocal.yaml 
apiVersion: tmp-redhatgov.com/v1alpha1
kind: ImageSetConfiguration
archiveSize: 1
storageConfig:
  local:
    path: /home/ocmirrortest/backend/output
mirror:
  ocp:
    channels:
      - name: stable-4.8
    graph: true

Run command : `oc-mirror --config imagesetbackendlocal.yaml file://output` will failed with error: error: decode tmp-redhatgov.com/v1alpha1, Kind=ImageSetConfiguration: json: unknown field "local"

Enter text here.
Attach the relevant portions of your `.openshift_bundle.log`.

# What you expected to happen?

Enter text here.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ your-commands-here
```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by jpower432** [comment]
:wave: @zhouying7780. The `local` field in the config is a relatively new addition. Added with this PR #192. Can you verify whether you still receive this error on the current main branch? Thanks!

**Comment by zhouying7780** [comment]
@jpower432 Tested with the latest code , can't reproduce now , I think we could close the issue now .
