### ISSUE TITLE
Stateless mode workspace cleanup

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#242]
# What happened?

Referencing a directory as a local backend that was previously used for stateless operations produces errors. 

# What you expected to happen?

Stateless mode should not leave any artifacts behind that inhibit normal operation of subsequent app runs. 

# How to reproduce it (as minimally and precisely as possible)?

mirror an ocp release to a directory in stateless mode. create local backend in imageset-config that references previous stateless mode output directory. mirror an ocp release again and the operation will generate a cincinnati retrieval error.

**Comment by jpower432** [comment]
@afflom Is this still an issue?
