### ISSUE TITLE
Default operator selection behavior

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#245]
1. If no packages listed, download the entire catalog at heads
2. If packages are listed without version or channel, download only the listed packages at channel heads
3. If packages are listed with versions but no channels specified, download that package version and required versions of each channel to channel head, including head.
4. If packages are listed with channels, download those channel head versions
5. If packages are listed with channels and versions, download the requested version and all versions to channel head, including head

**Comment by jpower432** [comment]
@afflom reminder that if this is not closed by TP, we need to update the docs to reflect current functionality

**Comment by afflom** [comment]
@jpower432 this is obsolete. I recommend closing.
