### ISSUE TITLE
Operator selection: starting version should fail on invalid version

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#270]
# What happened?

oc-mirror did not exit when an invalid starting version of an operator package was referenced. The resulting imageset did not include ANY versions of the specified operator.

# What you expected to happen?

Invalid referenced versions should cause oc-mirror to exit with an error.

**Comment by jpower432** [comment]
Related to #272

**Comment by afflom** [comment]
@david-rh Have any questions or need help with this?

**Comment by david-rh** [comment]
Submitted PR #354
