### ISSUE TITLE
Bug: channel must contain at least one bundle

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#272]
# What happened?

When trying to install an operator catalog into a cluster, the catalog container produced this error:
```
$ oc logs -f redhat-operator-index-km5tv
Error: could not build index model from declarative config: invalid index:
└── invalid package "cluster-logging":
    └── invalid channel "stable":
        └── channel must contain at least one bundle
```

# What you expected to happen?

The catalog container should not produce errors.

**Comment by jpower432** [comment]
Linked this error -> https://github.com/operator-framework/operator-registry/pull/905

If a version is provided that does not map to a bundle, this currently produces an empty package and that error. This will prune any empty packages. A follow-on PR to `oc-mirror` should be provided to alert the user that their `startingVersion` was invalid.
