### ISSUE TITLE
Terminated mirror run from: NoVersionsFound issue caused by look-ahead to an empty fast-4.10 channel

### ISSUE THREAD

**Issue by jimbarlow** [openshift/oc-mirror#292]
# Version

```console
$ oc-mirror version
v0.1.0-alpha.3
```

# What happened?
I have published two different "fast-4.8" channel upgrades to this cluster through my first three sequences 4.8.26 and 4.8.27.
In this next step, my fourth sequence, I attempted to mirror a version from the "fast-4.8" channel: 4.8.28
```
$ oc-mirror list releases --version=4.8 --channel=fast-4.8
Channel: fast-4.8
4.7.0
4.7.1
.
.
.
4.8.27
4.8.28
```
So created this imageset:
```
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: quay.jimbarlow.com/jimbarlow/metadata:oc-mirror
    skipTLS: false
mirror:
  ocp:
    channels:
      - name: fast-4.8
        versions:
          - '4.8.28'
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.8
      headsOnly: false
      packages:
        - name: quay-operator
          startingVersion: '3.5.7'
          channels:
            - name: quay-v35
```
The here is my command output:
```
$ oc-mirror --config imageset-4.8.28.yaml file://output-dir --log-level=debug
DEBUG Using registry backend at location quay.jimbarlow.com/jimbarlow/metadata:oc-mirror 
DEBUG Checking for existing metadata image at quay.jimbarlow.com/jimbarlow/metadata:oc-mirror 
DEBUG looking for metadata file at "publish/.metadata.json" 
INFO Found: output-dir/oc-mirror-workspace/src/publish 
INFO Creating directory: output-dir/oc-mirror-workspace/src/v2 
INFO Creating directory: output-dir/oc-mirror-workspace/src/charts 
INFO Downloading requested release 4.8.28         
DEBUG Found current release 4.8.27                 
DEBUG Processing channel fast-4.9                  
DEBUG Getting updates for latest 4.8.27 in channel fast-4.9 
DEBUG Processing channel fast-4.10                 
error: failed to get upgrade graph: NoVersionsFound: no cluster versions found in the "fast-4.10" channel
```
It doesn't matter if I use graph: true or graph:false (not sure it is implemented yet)

# What you expected to happen?
I expected that I would be able to mirror 4.8.28, without it failing because of a future 4.10 concern.

This issue can be consistently reproduced with my steps above.

# Anything else we need to know?
I would have expected a NoVersionsFound issue to be a warning rather than an error

**Comment by afflom** [comment]
@jimbarlow Great find. Thank you for submitting. I agree with noversionfound being a warning too. 

I tried to replicate this error, but found that this is only reproducible during differential operation. That validates our assumption that we would have to improve cincinnati calculations within oc-mirror, so we'll incorporate this issue into the work. Thanks again for submitting this.
