### ISSUE TITLE
[RFE] OCP + Operator Upgrade Graph Interpolation and Version Selection

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#303]
Problem: Operator version selection in oc-mirror may not be ideal. Several users have requested the ability to select an individual operator version within the imageset-config. Additionally, some operators are dependent on specific patch versions of OCP. 

Recommendation: We can solve both of the above issues at once by handling operator selection the same way that we currently handle cincinnati. oc-mirror currently allows for version selection of ocp releases and then maintains upgrade paths between declared ocp versions as annotated during differential operations. We can then use these declared and implicit versions to calculate which OCP releases need to be implicitly added to the imageset. This will also require additional calculations to ensure that OCP versions have upgrade paths.  

If no ocp release mirroring is configured within the imageset-config, then no interpolation would occur.

cc @dinhxuanvu @dmesser @jpower432

**Comment by dmesser** [comment]
I think that makes a lot of sense. We'd need to document the fact that `oc mirror` will likely need to download more than the two versions you are asking it to mirror in order to provide an update path between them - many users are not aware of the graph in daily usage.

**Comment by afflom** [comment]
That's a great point about the graph. I guess the start of the pruned graph would be the same as the genesis of cincinnati. Though I'm unclear what that looks like.

**Comment by jpower432** [comment]
This may also get complicated with cross-channel upgrades. This needs to be handled more gracefully by `oc-mirror` in terms of releases, but I would assume it would just as complex or even more so with operator upgrades.

**Comment by afflom** [comment]
Another great point. Maybe we only pull the required versions of ocp to satisfy the operator dependency from the ocp channel specified in the imageset-config. That also lends well to the idea that we do not implicitly mirror ocp releases for operators if there is no ocp mirroring configuration within the imageset-config.

**Comment by jpower432** [comment]
Removed from 4.11 milestone because there is currently no operator package annotation that would support this behavior. This will have to be re-evaluated after coordination with the OLM team.

**Comment by dmesser** [comment]
@jpower432 What kind of metadata do we need in order to support this?
