### ISSUE TITLE
[RFE] Red Hat vendor'd image for OPM framework.

### ISSUE THREAD

**Issue by ianwatsonrh** [openshift/oc-mirror#320]
Currently an upstream OPM image is used defined in the variable OPMImage such as quay.io/operator-framework/opm@sha256:d7eb3d6e652142a387a56d719d4ae33cd55028e42853691d3af895e7cbba9cd6.

Ideally a Red Hat vendor'd image would be used which can then be signature checked. 
Appreciated that no such image currently exists as far as I can see.

**Comment by jpower432** [comment]
@ianwatsonrh We are planning to replace this image. See #274. We plan to use the requested catalog as a base image instead of the upstream `opm` image going forward.

**Comment by ianwatsonrh** [comment]
Thanks, confirmed that a signature exists for said catalog images so can close this.
