### ISSUE TITLE
Add support for splitting the transfer artifacts by size

### ISSUE THREAD

**Issue by dmc5179** [openshift/oc-mirror#338]
Many users of the oc-mirror tool need to transfer data through processes that have a maximum transfer segment size. For example, DVDs. Add support for oc-mirror to split the resulting artifacts by maximum size and then stitch them back together when pushing content to the user's private registry solution.

Certainly users could split/cat the tar files manually but this feature will allow for an easier, and in some cases, more automatable way to transfer content from the internet connected side to their air-gapped environments.

**Comment by afflom** [comment]
This is already a feature of oc-mirror: 

https://github.com/openshift/oc-mirror/blob/6c00410b0895d93c39fad338fd48920b08bafca2/pkg/archive/archive.go#L75

https://github.com/openshift/oc-mirror/blob/6c00410b0895d93c39fad338fd48920b08bafca2/pkg/config/v1alpha1/config_types.go#L25

**Comment by dmc5179** [comment]
Feature already exists. Closing
