### ISSUE TITLE
Fix "illegal" characters used in file names in the oc-mirror git repo

### ISSUE THREAD

**Issue by jchunkins** [openshift/oc-mirror#344]
# Version

client version is not applicable to this issue.

# What happened?

Attempting to use `go get` on a Mac with this git repository resulted in a failure. There are test cases in this project that use file names that are not cross platform compatible (i.e. they use a colon character) which causes errors on the Mac (see below).

# What did you expect to happen?

Executing `go get` in my project should allow me to use code within the oc-mirror project.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ go get github.com/openshift/oc-mirror@17ed37d
go: downloading github.com/openshift/oc-mirror v0.1.1-alpha.3.0.20220302141825-17ed37d8943b
go get github.com/openshift/oc-mirror@17ed37d: create zip: pkg/cli/mirror/testdata/v2/single_manifest/blobs/sha256:e8614d09b7bebabd9d8a450f44e88a8807c98a438a2ddd63146865286b132d1b: malformed file path "pkg/cli/mirror/testdata/v2/single_manifest/blobs/sha256:e8614d09b7bebabd9d8a450f44e88a8807c98a438a2ddd63146865286b132d1b": invalid char ':'
pkg/cli/mirror/testdata/v2/single_manifest/manifests/sha256:d31c6ea5c50be93d6eb94d2b508f0208e84a308c011c6454ebf291d48b37df19: malformed file path "pkg/cli/mirror/testdata/v2/single_manifest/manifests/sha256:d31c6ea5c50be93d6eb94d2b508f0208e84a308c011c6454ebf291d48b37df19": invalid char ':'
pkg/image/testdata/v2/index_manifest/manifests/sha256:60f5921e0f6a21a485a0a4e9415761afb5b60814bbe8a6864cb12b90ae24c1d0: malformed file path "pkg/image/testdata/v2/index_manifest/manifests/sha256:60f5921e0f6a21a485a0a4e9415761afb5b60814bbe8a6864cb12b90ae24c1d0": invalid char ':'
pkg/image/testdata/v2/index_manifest/manifests/sha256:9574416689665a82cb4eaf43463da5b6156071ebbec117262eef7fa32b4d7021: malformed file path "pkg/image/testdata/v2/index_manifest/manifests/sha256:9574416689665a82cb4eaf43463da5b6156071ebbec117262eef7fa32b4d7021": invalid char ':'
pkg/image/testdata/v2/index_manifest/manifests/sha256:b8a825862d73b2f1110dd9c5fc0631f47117c7cd99e42efa34244cd82bd6742f: malformed file path "pkg/image/testdata/v2/index_manifest/manifests/sha256:b8a825862d73b2f1110dd9c5fc0631f47117c7cd99e42efa34244cd82bd6742f": invalid char ':'
pkg/image/testdata/v2/index_manifest/manifests/sha256:bab3a6153010b614c8764548f0dbe34c4a7dce4ea278a94713c3e9a936bb74e6: malformed file path "pkg/image/testdata/v2/index_manifest/manifests/sha256:bab3a6153010b614c8764548f0dbe34c4a7dce4ea278a94713c3e9a936bb74e6": invalid char ':'
pkg/image/testdata/v2/index_manifest/manifests/sha256:d15a206e4ee462e82ab722ed84dfa514ab9ed8d85100d591c04314ae7c2162ee: malformed file path "pkg/image/testdata/v2/index_manifest/manifests/sha256:d15a206e4ee462e82ab722ed84dfa514ab9ed8d85100d591c04314ae7c2162ee": invalid char ':'
pkg/image/testdata/v2/single_manifest/manifests/sha256:d31c6ea5c50be93d6eb94d2b508f0208e84a308c011c6454ebf291d48b37df19: malformed file path "pkg/image/testdata/v2/single_manifest/manifests/sha256:d31c6ea5c50be93d6eb94d2b508f0208e84a308c011c6454ebf291d48b37df19": invalid char ':'
```

# Anything else we need to know?

- As a work around I can use git to clone the repo on my local system (e.g. `/path/to/src/github.com/openshift/oc-mirror`) and do a replace in the go.mod file to point at my local repo.

```
replace (
	github.com/apcera/gssapi => github.com/openshift/gssapi v0.0.0-20161010215902-5fb4217df13b
	github.com/openshift/oc-mirror => /path/to/src/github.com/openshift/oc-mirror
)
```

- My suggestion would be to either rename your files so they are cross platform compatible (e.g. use a hyphen) or put your test data into an archive and extract it (but only allow the test to run on the platform you intend these tests to work on). I am sure there are other alternatives too.

# References

None

**Comment by afflom** [comment]
Related #199

**Comment by afflom** [comment]
HI @jchunkins , Thank you for bringing this to our attention. I've linked a related PR where another contributor was preparing to enable oc-mirror development on mac. Would you be able to collaborate with @SDBrett on that or PR your own fix?

**Comment by jchunkins** [comment]
Found another workaround (but have not tested it) based on this comment https://github.com/golang/go/issues/41402#issuecomment-832735435

> You can exclude directories containing test data and other large files by placing a go.mod file (even an empty one) at the top of it.

**Comment by jchunkins** [comment]
/reopen

The offending files are still present, so this is probably still relevant

**Comment by jchunkins** [comment]
This was merged. Closing
