### ISSUE TITLE
[RFE] Ability to mirror from alternate registry location via registries.conf 

### ISSUE THREAD

**Issue by morstad** [openshift/oc-mirror#356]
**Description** : Request support for alternate registry location to be specified via registries.conf during pre-production disconnected testing / validation.  This allows teams to reference the final production location of images always in catalogs, ImageSetConfigs, etc.  

Example /etc/containers/registries.conf with redirection from production to preproduction location: 
```
[[registry]]
 location = "prodlocation.io/xx"
 insecure = false
 blocked = false
 mirror-by-digest-only = true
 prefix = ""
 [[registry.mirror]]
  location = "preprodlocation/xx"
  insecure = false
```

**Use Case** : Validating disconnected support for operator prior to General Availability (GA).

**Workaround/Alternative** : Manipulate image references in catalog(s) and ImageSetConfig(s) during disconnected verification based on state of release (pre-GA vs GA) or utilize alternative image mirroring / verification process  prior to GA (i.e. potentially extract image list from `oc-mirror --dry-run`, mirror with skopeo which honors registries.conf, build offline catalog, ...) - issue is not testing customer path.

**Comment by afflom** [comment]
Hi @morstad! I think that this makes sense and is what users would expect from oc-mirror. Thank you for submitting this. 

@jpower432 any thoughts?

**Comment by jpower432** [comment]
@afflom Sorry for the delayed response. I agree that `oc-mirror` should support registry mirrors. The only possible issue is that some of the keys overlap with `oc-mirror` flags. Adding this requires some UX refining. Other than that, I think the use-case is valid and this should be added to the backlog.

**Comment by joehuizenga** [comment]
fyi, created this ticket in the openshift-oc repo
https://github.com/openshift/oc/issues/1163

**Comment by morstad** [comment]
Believe this is now covered under https://issues.redhat.com/browse/WRKLDS-468?page=com.docminer.jira.issue-links%3Acom.kintosoft.jira.links.tab-panel
