### ISSUE TITLE
error: error parsing mirror registry "LOCALHOST:5000": "LOCALHOST:5000" is not a valid image reference: repository name must be lowercase

### ISSUE THREAD

**Issue by midu16** [openshift/oc-mirror#361]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"0", Minor:"2", GitVersion:"v0.2.0-alpha.1", GitCommit:"4de61d62fd3a76a70abf4a46c178397be42974cd", GitTreeState:"clean", BuildDate:"2022-03-14T12:47:36Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

oc mirror --from ./archive/ docker://LOCALHOST:5000/olm-mirror --dest-skip-tls --dest-use-http
INFO Checking push permissions for LOCALHOST:5000 
INFO Publishing image set from archive "./archive/" to registry "LOCALHOST:5000" 
WARNING metadata has single-use label, using stateless mode 
INFO No existing metadata found. Setting up new workspace 
error: error parsing mirror registry "LOCALHOST:5000": "LOCALHOST:5000" is not a valid image reference: repository name must be lowercase

Attach the relevant portions of your `.oc-mirror.log`.
time="2022-03-16T13:58:39+01:00" level=info msg="Checking push permissions for LOCALHOST:5000"
time="2022-03-16T13:58:39+01:00" level=debug msg="Using image LOCALHOST:5000/olm-mirror/oc-mirror to check permissions"
time="2022-03-16T13:58:39+01:00" level=info msg="Publishing image set from archive \"./archive/\" to registry \"LOCALHOST:5000\""
time="2022-03-16T13:58:39+01:00" level=debug msg="Unarchiving metadata into oc-mirror-workspace/images.690595667"
time="2022-03-16T13:58:39+01:00" level=debug msg="Found archive archive/mirror_seq1_000000.tar"
time="2022-03-16T13:58:39+01:00" level=debug msg="Extracting archive archive/mirror_seq1_000000.tar"
time="2022-03-16T13:58:39+01:00" level=debug msg="looking for metadata file at \"publish/.metadata.json\""
time="2022-03-16T13:58:39+01:00" level=warning msg="metadata has single-use label, using stateless mode"
time="2022-03-16T13:58:39+01:00" level=debug msg="Using local backend at location oc-mirror-workspace"
time="2022-03-16T13:58:39+01:00" level=debug msg="looking for metadata file at \"publish/.metadata.json\""
time="2022-03-16T13:58:39+01:00" level=info msg="No existing metadata found. Setting up new workspace"
time="2022-03-16T13:58:39+01:00" level=debug msg="Unpacking any provided Helm charts to oc-mirror-workspace/results-1647435519"

# What did you expect to happen?

I was expecting that since the capital hostname are resolved also the oc-mirror cli to be able to do so.
$ ping -c 4LOCALHOST
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.036 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.052 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.099 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.098 ms
--- localhost ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3107ms
rtt min/avg/max/mdev = 0.036/0.071/0.099/0.028 ms

# How to reproduce it (as minimally and precisely as possible)?

```console
$ podman run --privileged -d --name registry -p 5000:5000 -v /opt/registry/data/:/var/lib/registry --restart=always registry:2
$ oc-mirror --from ./archive/ docker://LOCALHOST:5000/olm-mirror --dest-skip-tls --dest-use-http
```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by afflom** [comment]
Thank you for using oc-mirror and submitting this issue! 

Can you please provide some details and use cases for using `LOCALHOST` as opposed to `localhost` or `$HOSTNAME`?
