### ISSUE TITLE
4.11 Req: migrate to klogv2

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#368]
You should not need [k8s.io/klog](http://k8s.io/klog) v1, none of k8s should be using it at this point in time.

klog/v2 even though a bit limited should be preferred for logging over any other solution.

**Comment by jpower432** [comment]
@sfxworks The dep change includes a change in the flags because of the difference between setting the level with `logrus` and `klog`. `log-level` will need to be replaced with `-v=X` X being 1-9.
