### ISSUE TITLE
The --help usage section should show how/why the file or docker value is used

### ISSUE THREAD

**Issue by patrickstrick** [openshift/oc-mirror#426]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"0", Minor:"1", GitVersion:"v0.1.0", GitCommit:"46dd96b5df44f908e3b5b72fe94bfb108ad73870", GitTreeState:"clean", BuildDate:"2022-04-02T04:55:39Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

When running `oc mirror --help` the destination (file or docker) is not documented except in the examples.
Are they commands? Are they part of the `oc mirror` basic Usage? Are they a Flag? They should be documented in one of those core sections.

# What did you expect to happen?

I expected the command syntax to be fully documented in the --help

# How to reproduce it (as minimally and precisely as possible)?

```console
oc mirror --help
```

**Comment by jpower432** [comment]
Thanks for the feedback @patrickstrick. This is absolutely spot on. I have submitted a PR address this immediate need and more/better documentation of the workflows is coming on #415.
