### ISSUE TITLE
Missing entries in imageContentSourcePolicy.yaml

### ISSUE THREAD

**Issue by marpears** [openshift/oc-mirror#449]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-26-g6d68758", GitCommit:"6d68758", GitTreeState:"clean", BuildDate:"2022-05-09T14:54:45Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

The imageContentSourcePolicy.yaml file produced by the oc-mirror tool is missing entries and only seems to include top level entries. When using oc adm catalog mirror the top level and lower level entries are included in the imageContentSourcePolicy.yaml file. 

For example, the oc-mirror log shows an image being mirrored to the registry

.oc-mirror.log

```
uploading: [myregistry.co.uk:5004/rhacm2/kube-state-metrics-rhel8](http://myregistry.co.uk:5004/rhacm2/kube-state-metrics-rhel8) sha256:7f98061eced566acfa4041b49f2e574a81e91be6d72791aac71342ebb81871eb 14.37MiB
```

But the imageContentSourcePolicy created only has the top level rhacm2 folder :
```
- mirrors:
  - [myregistry.co.uk:5004/rhacm2](http://myregistry.co.uk:5004/rhacm2)
  source: [registry.redhat.io/rhacm2](http://registry.redhat.io/rhacm2)
```

# What did you expect to happen?

When mirroring using oc adm catalog mirror, the imageContentSourcePolicy creates entries for each of the images mirrored. I would expect oc-mirror to behave the same:

```
  - mirrors:
    - [myregistry.co.uk:5004/rhacm2/rhacm2-kube-state-metrics-rhel8](http://myregistry.co.uk:5004/rhacm2/rhacm2-kube-state-metrics-rhel8)
    source: [registry.redhat.io/rhacm2/kube-state-metrics-rhel8](http://registry.redhat.io/rhacm2/kube-state-metrics-rhel8)
```

# How to reproduce it (as minimally and precisely as possible)?

Mirror images into a local repository and check that the imageContentSourcePolicy.yaml file includes entries for each of the images mirrored with their full path.

# Anything else we need to know?

# References

**Comment by afflom** [comment]
Hi @marpears. The ICSP example that you posted is a valid ICSP for all images contained within the rhacm2 namespace. The cluster with this ICSP installed will be able to pull any image that starts with `registry.redhat.io/rhacm2` from `myregistry.co.uk:5004/rhacm2`
