### ISSUE TITLE
[bug] m2m completes successfully when publishing to incorrect namespace

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#468]
# Version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-36-g7d88d4e", GitCommit:"7d88d4e8", GitTreeState:"clean", BuildDate:"2022-05-16T20:28:02Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

# What happened?

when publishing m2m differential synchronizations, if an incorrect namespace is targeted for publishing, oc-mirror does not produce a sequence error as expected. 

# What did you expect to happen?

differential syncs should error if published to a different registry namespace than previous syncs. 

# How to reproduce it (as minimally and precisely as possible)?

publish a to a mirror registry namespace and then use m2m to publish a diff to a different namespace.

**Comment by jpower432** [comment]
In this instance a new workspace would be created. If the sequence number is not #1, there would be an error. So this should only happen in the instance where a imageset was published for the first time in one namespace and then subsequently in another. I would not like to add this constraint as publishing with different namespace is a tactic being used for image promotion. WDYT?

**Comment by jpower432** [comment]
If I am missing the error, can you please post a copy of the log?

**Comment by jpower432** [comment]
Discussed out of band. The solution would be to disallow the publishing of a differential imageset if there is no instance of metadata in the target namespace.
