### ISSUE TITLE
Operator defaultChannel changes not flagged to user

### ISSUE THREAD

**Issue by ianwatsonrh** [openshift/oc-mirror#480]
# Version

```console
$ oc-mirror version
<your output here>
```

# What happened?

When a operator changes its default channel and the imageset is not configured to import this default channel a error will occur when trying to spin up the pruned index container.

For example quay-bridge-operator has recently changed its defaultChannel to stable-3.7. 

If you had a imageset such as 
- name: quay-bridge-operator
          channels:
            - name: stable-3.6

Then next time you import, your new pruned index will fail with a message like

Error: could not build index modelfrom declarative config: invalid index:
  invalid package "quay-bridge-operator"
    invalid channel "stable-3.7"
      channel must contain at least one bundle

Should his happen and you need to fix it quickly to update other operators you can pull /  extract the index.json / change the defaultChannel back to stable-3.6 / repush the pruned container. 

A solution for now is to then go back and add the missing default channel into your image set and perform another mirror. 

A longer term solution however is required to catch this error before the user has mirrored in the content to their disconnected environment.

Possible options: 
- always mirror in the defaultChannel. 
- error out until the user addresses the issue in their imageset
- modify the defaultChannel argument

**Comment by jpower432** [comment]
@ianwatsonrh We have two PRs to address this #464 and #478. Uses option 2.

**Comment by jpower432** [comment]
Related to #459
