### ISSUE TITLE
missing blobs

### ISSUE THREAD

**Issue by tjmapley** [openshift/oc-mirror#491]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-41-gf93ddac", GitCommit:"f93ddac", GitTreeState:"clean", BuildDate:"2022-05-20T15:57:49Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

Attempted to mirror `4.10.15` with:

```
rm -rf archive
rm -rf publish
oc-mirror --config config.yaml file://archive -v 9
```
and `config.yaml`:
```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
      minVersion: 4.10.15
      maxVersion: 4.10.15
```
oc-mirror completed without error, but several files were skipped:

```
Blob sha256:237bfbffb5f297018ef21e92b8fede75d3ca63e2154236331ef2b2a9dd818a02 exists in imageset, skipping...
Blob sha256:39382676eb30fabb7a0616b064e142f6ef58d45216a9124e9358d14b12dedd65 exists in imageset, skipping...
Blob sha256:804449b22e26cc93ec79fad318d5af873434fe344ccaf377c2487df2ad851776 exists in imageset, skipping...
Adding blob sha256:98f1d706f38e267926dddf47c4aa39a048999baaf3a455e35c5b0dfdaaf677fe
Blob sha256:a7635174fc67fd997681528eb831bf1c492bbb6b30ffd430aca98a9a89975bab exists in imageset, skipping...
Blob sha256:c692ab5b8175b380a4fffc7e41f537219c90207fdfedf5ab337525b1f69024e1 exists in imageset, skipping...
...
File v2/openshift/release-images/blobs/sha256:237bfbffb5f297018ef21e92b8fede75d3ca63e2154236331ef2b2a9dd818a02 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:39382676eb30fabb7a0616b064e142f6ef58d45216a9124e9358d14b12dedd65 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:804449b22e26cc93ec79fad318d5af873434fe344ccaf377c2487df2ad851776 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:98f1d706f38e267926dddf47c4aa39a048999baaf3a455e35c5b0dfdaaf677fe added to archive
File v2/openshift/release-images/blobs/sha256:a7635174fc67fd997681528eb831bf1c492bbb6b30ffd430aca98a9a89975bab will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:c692ab5b8175b380a4fffc7e41f537219c90207fdfedf5ab337525b1f69024e1 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:ddcb70ce04a01ce487c0f4ad769e9e36a10c8c832a34307c1b1eb8e03a5b7ddb added to archive

```
Then I mirrored some operators. So I had 2 tar files.

On the disconnected network, the first tar applied, but the 2nd tar complained about not having the blobs that were skipped in the first run above.

# What did you expect to happen?

Be able to apply tar files in sequence on the disconnected network.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ oc-mirror --config config.yaml file://archive -v 9 # with config.yaml above
```

# Anything else we need to know?

# References

**Comment by jpower432** [comment]
@tjmapley Do you have access to the log in the disconnected environment? If so, can you please provide that? Can you also please provide the second configuration you were testing with?

**Comment by tjmapley** [comment]
thanks! we'll be using the new version for sure

**Comment by tjmapley** [comment]
I am pretty sure the blobs are still being skipped. I cloned and built today and the same blobs were noted in the logs as skipped.

```bash
oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.2.0-alpha.1-58-g3c1c80c", GitCommit:"3c1c80ca", GitTreeState:"clean", BuildDate:"2022-06-25T11:07:53Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
File v2/openshift/release-images/blobs/sha256:237bfbffb5f297018ef21e92b8fede75d3ca63e2154236331ef2b2a9dd818a02 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:39382676eb30fabb7a0616b064e142f6ef58d45216a9124e9358d14b12dedd65 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:4a5879bbd954da3d9d14db4c9cca70f0dd0ff2dcb5e5c1dfbd2edeefc866dc7f will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:df37870c9b590d1df90ae85c5186370452cb17de6e25f22b683b5f3a2f4dc1d5 will not be archived, skipping...
File v2/openshift/release-images/blobs/sha256:f70cb1865d54b2ff4ae0de4eccc872d16704750c6b1d03b9a61e68f9a7bcdab2 will not be archived, skipping...
File v2/openshift/release-images/manifests will not be archived, skipping...
```

Here is my config. Note that I was mirroring OCP 4.10.17 as opposed to 4.10.15:
```
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: stable-4.10
      type: ocp
      minVersion: 4.10.17
      maxVersion: 4.10.17
```

**Comment by tjmapley** [comment]
I put a breakpoint on `pkg/archive/archive.go:260` `func includeFile(fpath string) bool`

Presumably this is once all fetching finished and now archiving (to the tar files?) is determined.

At this point for 4.10.17, this is what my workspace looks like:

```
[tjm@ae oc-mirror-workspace]$ cd src
[tjm@ae src]$ ls
charts  publish  release-signatures  v2
[tjm@ae src]$ ls -la
total 0
drwxrwxr-x. 7 tjm tjm 100 Jun 25 12:47 .
drwxrwxr-x. 3 tjm tjm  17 Jun 25 12:36 ..
drwxrwxr-x. 2 tjm tjm   6 Jun 25 12:36 charts
drwxrwxr-x. 2 tjm tjm   6 Jun 25 12:36 publish
drwxrwxr-x. 2 tjm tjm  52 Jun 25 12:36 release-signatures
drwxrwxr-x. 3 tjm tjm  21 Jun 25 12:47 tmpbackend.1656175632
drwxrwxr-x. 3 tjm tjm  23 Jun 25 12:36 v2
[tjm@ae src]$ find tmpbackend.1656175632/
tmpbackend.1656175632/
tmpbackend.1656175632/publish
tmpbackend.1656175632/publish/.metadata.json
[tjm@ae src]$ find . -name release-images
./v2/openshift/release-images
[tjm@ae src]$ cd ..
[tjm@ae oc-mirror-workspace]$ cd ..
[tjm@ae archive]$ ls
mirror_seq1_000000.tar  oc-mirror-workspace
[tjm@ae archive]$ ls -la
total 252
drwxr-x---.  3 tjm tjm     63 Jun 25 12:47 .
drwxrwxr-x. 15 tjm tjm   4096 Jun 25 12:36 ..
-rw-rw-r--.  1 tjm tjm 252148 Jun 25 12:47 mirror_seq1_000000.tar
drwxrwxr-x.  3 tjm tjm     17 Jun 25 12:36 oc-mirror-workspace
[tjm@ae archive]$ find . -name release-images
./oc-mirror-workspace/src/v2/openshift/release-images
[tjm@ae archive]$ find ./oc-mirror-workspace/src/v2/openshift/release-images
./oc-mirror-workspace/src/v2/openshift/release-images
./oc-mirror-workspace/src/v2/openshift/release-images/blobs
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:df37870c9b590d1df90ae85c5186370452cb17de6e25f22b683b5f3a2f4dc1d5
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:f70cb1865d54b2ff4ae0de4eccc872d16704750c6b1d03b9a61e68f9a7bcdab2
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:4a5879bbd954da3d9d14db4c9cca70f0dd0ff2dcb5e5c1dfbd2edeefc866dc7f
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:237bfbffb5f297018ef21e92b8fede75d3ca63e2154236331ef2b2a9dd818a02
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:f66b3c5faf19d24c2b51f100fd4981b2267a2e212b4a4ffe13ef554fe0418b5b
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:59ffcf9df278e40681e261e3f777f540831d85f3cdd9ea0291702dc318c7f54a
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:39382676eb30fabb7a0616b064e142f6ef58d45216a9124e9358d14b12dedd65
./oc-mirror-workspace/src/v2/openshift/release-images/blobs/sha256:87d800b3f7c657ed6f18c920f7c925df91b000805366bee068de3625807abd33
./oc-mirror-workspace/src/v2/openshift/release-images/manifests
./oc-mirror-workspace/src/v2/openshift/release-images/manifests/sha256:87d800b3f7c657ed6f18c920f7c925df91b000805366bee068de3625807abd33
./oc-mirror-workspace/src/v2/openshift/release-images/manifests/4.10.17-x86_64
```

It is odd that just a few blobs are in `release-images`. Is that an issue with the registry/repository?

Either that or it seems like `oc-mirror` should include these blobs.

Last time and this time `oc-mirror` completed with success while skipping the blobs. The problem is in applying the 2nd tar file that is counting on these blobs.

**Comment by tjmapley** [comment]
Some of the 'blobs' from the `release-images` dir are being included. Notice that the files that are complained about being missing and skipped are the small ones: 

```
[tjm@ae blobs]$ pwd
…archive/oc-mirror-workspace/src/v2/openshift/release-images/blobs
[tjm@ae blobs]$ ls -la
total 135996
drwxr-xr-x. 2 tjm tjm     4096 Jun 25 12:47 .
drwxr-xr-x. 4 tjm tjm       36 Jun 25 12:47 ..
-rw-------. 1 tjm tjm 83368540 Jun 25 12:38 sha256:237bfbffb5f297018ef21e92b8fede75d3ca63e2154236331ef2b2a9dd818a02
-rw-------. 1 tjm tjm     1462 Jun 25 12:47 sha256:39382676eb30fabb7a0616b064e142f6ef58d45216a9124e9358d14b12dedd65
-rw-------. 1 tjm tjm 23866110 Jun 25 12:45 sha256:4a5879bbd954da3d9d14db4c9cca70f0dd0ff2dcb5e5c1dfbd2edeefc866dc7f
-rw-------. 1 tjm tjm   612981 Jun 25 12:47 sha256:59ffcf9df278e40681e261e3f777f540831d85f3cdd9ea0291702dc318c7f54a
-rw-------. 2 tjm tjm     1583 Jun 25 12:47 sha256:87d800b3f7c657ed6f18c920f7c925df91b000805366bee068de3625807abd33
-rw-------. 1 tjm tjm 20183939 Jun 25 12:42 sha256:df37870c9b590d1df90ae85c5186370452cb17de6e25f22b683b5f3a2f4dc1d5
-rw-------. 1 tjm tjm     1772 Jun 25 12:47 sha256:f66b3c5faf19d24c2b51f100fd4981b2267a2e212b4a4ffe13ef554fe0418b5b
-rw-------. 1 tjm tjm 11203064 Jun 25 12:37 sha256:f70cb1865d54b2ff4ae0de4eccc872d16704750c6b1d03b9a61e68f9a7bcdab2
```

**Comment by jpower432** [comment]
Hi @tjmapley, out of curiosity, could you try running the command with `--ignore-history` that will avoid skipping blobs. I want to determine if the problem is during workspace reconciliation or archiving. Can you also post a copy of the full log, please?

**Comment by tjmapley** [comment]
Hi @jpower432 - thanks for helping us with this and sorry it took so long for me to get back to trying this again. I ran a few minutes ago and got the same results. I also ran with `--ignore-history` and got the same results.

Here is the sequence
1. pull from main
2. build
3. ensure correct version with `bin/oc-mirror version` and file modification time
4. replace old oc-mirror on `PATH`
5. `oc-mirror --config config.yaml file://archive -v 9` config.yaml targeted ocp 4.10.17 and no operators, no ancillary, and no charts. In our workflow, this is the first run. Subsequent runs we would add operators. This finished w/o errors.
6. `grep -i skipping log.txt` -- this shows the same blobs skipped as last time
7. `rm -rf publish archive`
8. `oc-mirror --config config.yaml --ignore-history file://archive -v 9` . As far as I can tell, this was indistinguishable from running without `--ignore-history`. I haven't read the docs, but would `--ignore-history` apply to runs 2-n (not first run)?
9. `grep -i skipping log.txt` -- this shows the same blobs skipped as last time

I screen recorded the whole thing and can pass that. Also I can pass the logs to you, but I'd rather not publicly because there is alot of log output. I am pretty sure there is nothing sensitive, but I'd rather email or something like that than attach here.

**Comment by tjmapley** [comment]
Here is an unlisted youtube video of what I did: https://youtu.be/w0AYItDcMuM

**Comment by tjmapley** [comment]
@jpower432 This is the first run. Does that matter? Our base run consists of OCP and then we put operators, ancillary, and what not on top. On the 2nd or later run I understand why blobs would be skipped. But we aren't building off any other runs and these same blobs are the ones that were referenced in the errors when applying the _2nd_ archive on our disconnected network. The fear is that these are something basic that will be referenced in the 2nd+ runs. When we got the error the first time the sequence was:
1. apply 1st run. no problem
2. apply 2nd run. errors complaining about blobs that were `skipped` in the first run

If you think a 2nd+ run won't fail referencing the blobs skipped in the first run, I'd be glad to apply these to the disconnected network. I was holding off because it is a tedious process and outwardly (logs) it _looks_ like it will happen again because of the same root logs that I thought it tracked down to before.

**Comment by tjmapley** [comment]
@jpower432 sent the logs to the email in your commits

**Comment by afflom** [comment]
There is a potential for many layers to be shared between container images. The notice about blobs being skipped is informing you that those layers have already been packed into the imageset previously and that they are being deduplicated.

**Comment by tjmapley** [comment]
@afflom @jpower432  thank you
