### ISSUE TITLE
Is aarch64 or arm64 supported?   OCP has those images.

### ISSUE THREAD

**Issue by schmaustech** [openshift/oc-mirror#500]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.11.0-202208020235.p0.g3c1c80c.assembly.stream-3c1c80c", GitCommit:"3c1c80ca6a5a22b5826c88897e7a9e5acd7c1a96", GitTreeState:"clean", BuildDate:"2022-08-02T04:04:36Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

Seems aarch64 or arm64 do not work as architecture types?

# What did you expect to happen?

Pull down arm64 or aarch64 images for openshift.

# How to reproduce it (as minimally and precisely as possible)?

```console
$ cat architecture-imageset-configuration.yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    architectures:
      - "arm64"
    channels:
      - name: stable-4.11
$ oc-mirror --config=architecture-imageset-configuration.yaml docker://provisioning.schmaustech.com:5000 --dest-skip-tls --dry-run
Checking push permissions for provisioning.schmaustech.com:5000
error: invalid configuration: release architecture "arm64" is not a supported architecture

```

# Anything else we need to know?

Enter text here.

# References

Enter text here.

**Comment by jpower432** [comment]
@schmaustech Thanks for pointing this out. There was an extra layer checking the release architectures (which did not have an all-inclusive list) in the config that I removed in a PR to let the Cincinnati APs determine valid architecture submissions.
