### ISSUE TITLE
[RFE] make custom auth.json location possible.

### ISSUE THREAD

**Issue by kristvanbesien** [openshift/oc-mirror#537]
# What happened?

I am using a custom location for my authentication file, by setting a REGISTRY_AUTH_FILE env variable.

podman login picks this up, but oc-mirror does not. This leads to confusing situations where podman login succeeds, but you then get a authentication when running oc-mirror.

So consider making oc-mirror aware of the REGISTRY_AUTH_FILE variable.

**Comment by nnachefski** [comment]
I second this.  The same --authfile parameter used by podman and skopeo would be nice...

**Comment by kristvanbesien** [comment]
I third this. I lost several hours because of this today... This is not very intuitive...

**Comment by jritter** [comment]
I'm also missing the feature to configure the auth.json for oc-mirror. It would make automation around oc-mirror much more simple and clear. Thanks for considering this feature!
