### ISSUE TITLE
Add options to set temporary directory

### ISSUE THREAD

**Issue by tinsjourney** [openshift/oc-mirror#561]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"0", Minor:"1", GitVersion:"v0.1.0", GitCommit:"a0b40626d40628c6e6fdd86e19995f7b7ed0e16c", GitTreeState:"clean", BuildDate:"2022-12-07T02:55:38Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

By default oc-mirror write to /tmp, but if /tmp is too small it will crash with "no space left" message

# What did you expect to happen?

change temporary director

# How to reproduce it (as minimally and precisely as possible)?

```console
$ oc-mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.10 --package=elasticsearch-operator
FATAL render reference "registry.redhat.io/redhat/redhat-operator-index:v4.10": write /tmp/render-unpack-3494781027/usr/lib64/libcrypto.so.1.1.1g: no space left on device
```

# Anything else we need to know?

In my use case /tmp is only 1G

# References

Enter text here.

**Comment by jritter** [comment]
I ran into the exact same issue, the option to define a temporary directory would be awesome.

**Comment by indor79** [comment]
As a workaround you could try setting the TMPDIR environment variable. 

` export TMPDIR=/var/tmp; oc mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.10 --package=elasticsearch-operator`

**Comment by tkagn** [comment]
Disabling tmpfs mount for `/tmp` resolved this issue for me: 

`systemctl mask tmp.mount`
reboot

tmp will be mounted on root (/tmp) and did not return any errors when running the mirror.
