### ISSUE TITLE
Install ICSP/CatalogSource Files

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#59]
This is a delicate procedure. We need to make sure that we nail the logic on this. The logic needs to be clarified, but this is a rough guess:

1. patch override operator hub
2. update icmp for ocp releases, images referenced in the catalogs, and other arbitrary images in the imageset. 
3. check installed operator versions and verify upgrade path to new catalog. Error if operators will become orphaned.
4. once operators are upgradable to new catalog version, upgrade ocp
5. patch override operator hub
6. upgrade operators from new catalog version

For the record, I am not saying that we should be triggering cluster upgrades from this application. Also, some of this might be handled by CVO or OLM. So some of this might not be handled by this app, but some of these objects need to be managed by us.

**Comment by dmesser** [comment]
Can we actually reliably do this? We don't know where the cluster or how many clusters are going to be installed based on this. Also different clusters need different ICSPs based on their versions.

**Comment by afflom** [comment]
@dmesser, From our offline convo, I'll backlog this for now.

**Comment by jpower432** [comment]
@afflom I think we have deemed this RFE as out of scope for `oc-mirror`. Do you agree? Safe to close?

**Comment by afflom** [comment]
I'd personally like to see an oc-mirror k8s controller that has this capability. It should have at least two modes of operation:

Spoke clusters: The controller would read the oc-mirror metadata from a mirror registry and render and apply the k8s resources to the cluster where it resides. It makes even more sense with oc-mirror being published to the ocp payload. 

Hub clusters: same as above, but would also perform the registry maintenance (publish/delete)
