### ISSUE TITLE
RFE The resulted ICSP should contain details for all operators not just for newly added

### ISSUE THREAD

**Issue by stefanvasilic4** [openshift/oc-mirror#597]
# Version
latest

# What happened?
When adding a new operator or change maxVersion in `imagesetconfiguration` the resulting ICSP has only the new operator details.

# What did you expect to happen?
I expect the new ICSP to contain details of existing operators plus the new operator's details, added to `imagesetconfiguration`

**Comment by pwcazenave** [comment]
This has caught me in the past - having only the details for the operators that were updated instead of all the requested operators  means I have to manually merge my ICSP configs after mirroring.

**Comment by ChristianLoewel** [comment]
Same for me - I have set the `--ignore-history` parameter to always mirror the complete catalog to ensure that removed ICSP entries are not lost, although this unnecessarily increases the runtime of oc-mirror.

**Comment by mnorrsken** [comment]
I have the same problem, as we are using gitops to update the ICSPs in the cluster

**Comment by dadav** [comment]
We have the same problem. We run oc-mirror daily and therefore have dozens of results directory with manifests which same names (e.g. operator-0). So if I apply these manifests which only contain a subset of the needed informations, everything else is lost.

**Comment by sushil-telus** [comment]
Looks like this is implemented

Ref:
- https://issues.redhat.com/browse/RFE-3000
- https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-openshift-cli_release-notes

Well I haven't tested it yet. (just in case anybody else is desperate for an update.)
