### ISSUE TITLE
"could not parse reference:" Error while Mirroring an image set to a mirror registry using oc-mirror

### ISSUE THREAD

**Issue by MadhuMahalingappa** [openshift/oc-mirror#643]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.13.0-202305091542.p0.gbee629a.assembly.stream-bee629a", GitCommit:"bee629ab1414e77a5f8455e816655355a7f280af", GitTreeState:"clean", BuildDate:"2023-05-09T16:58:42Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

```

# What happened?

when running oc mirror command the same fails with parse error

oc mirror --config=imageset-config.yaml docker://nexus-repo.intern:8084 --dest-skip-tls 
Checking push permissions for nexus-repo.intern:8084
Creating directory: oc-mirror-workspace/src/publish
Creating directory: oc-mirror-workspace/src/v2
Creating directory: oc-mirror-workspace/src/charts
Creating directory: oc-mirror-workspace/src/release-signatures
error: parsing reference "": could not parse reference:

# What did you expect to happen?

Mirroring an image set to a mirror registry completion successful 

# How to reproduce it (as minimally and precisely as possible)?

1. oc mirror init --registry nexus-repo.intern:8084 > imageset-config.yaml

2. oc mirror --config=imageset-config.yaml docker://nexus-repo.intern:8084 --dest-skip-tls 
Checking push permissions for nexus-repo.intern:8084
Creating directory: oc-mirror-workspace/src/publish
Creating directory: oc-mirror-workspace/src/v2
Creating directory: oc-mirror-workspace/src/charts
Creating directory: oc-mirror-workspace/src/release-signatures
error: parsing reference "": could not parse reference:

# References

Enter text here.

**Comment by grantcurell** [comment]
Some problem here - did this ever get addressed?

**Comment by realcaptain** [comment]
> Some problem here - did this ever get addressed?

Have you checked the "storageConfig.registry.imageURL" in the imageset-config.yaml? Ensure the imageURL value is correctly formatted and includes a valid registry URI and namespace. For example, 

storageConfig:
  registry:
    imageURL: "test.registry/mrorg/"

https://docs.openshift.com/container-platform/4.16/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-imageset-config-params_installing-mirroring-disconnected:~:text=storageConfig.registry.imageURL
