### ISSUE TITLE
Each output starts with "Logging to .oc-mirror.log"

### ISSUE THREAD

**Issue by muellerfabi** [openshift/oc-mirror#710]
# Version
```console
$ oc-mirror version 
Logging to .oc-mirror.log
WARNING: This version information is deprecated and will be replaced with the output from --short. Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.14.0-202310091027.p0.g68cf97e.assembly.stream-68cf97e", GitCommit:"68cf97ec715ad2d78fb2bac411a118709c191719", GitTreeState:"clean", BuildDate:"2023-10-09T17:32:12Z", GoVersion:"go1.20.5 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

You already see the issue in the version output. Each and every output starts with "Logging to .oc-mirror.log"

# How to reproduce it (as minimally and precisely as possible)?

Run any oc-mirror command that outputs something

**Comment by BadgerOps** [comment]
Just ran into this as well, this is especially annoying when using the `oc-mirror init > imageset.yaml` feature, as it prepends the yaml file with that output, which caused some failures till we identified it:

```bash
$ head imageset.yaml

Logging to .oc-mirror.log
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
<snip>
```

Either the documentation in https://docs.openshift.com/container-platform/4.12/installing/disconnected_install/installing-mirroring-disconnected.html should be updated, or the `oc-mirror` tool should not add extra lines to output.
