### ISSUE TITLE
Allow oc mirror without default channel in imagesetconfiguration

### ISSUE THREAD

**Issue by Skalador** [openshift/oc-mirror#724]
# Version

```console
# oc version
Client Version: 4.14.1
Kustomize Version: v5.0.1

# oc-mirror version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"4.12.0-202303231115.p0.g3d51740.assembly.stream-3d51740", GitCommit:"3d517407dcbc46ededd7323c7e8f6d6a45efc649", GitTreeState:"clean", BuildDate:"2023-03-24T03:25:44Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

The oc-mirror tool requires the default channel to be present in the Imagesetconfiguration file. This constraint makes it difficult to maintain up-to-date imagesetconfigurations for disconnected environments. From my point of view it does not make any sense, to always include the latest version of the operator, especially when I do not want to use it (due to version freezing on our side). I would propose to either automatically include the latest version or remove the requirement of the default channel.

Please Note: Currently we update the imagesetconfiguration files with a python script, but running an `oc mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.12 --package=<operator-name>` command for each operator takes several minutes just to fetch the default channel. This circumstance makes it cumbersome to maintain an imagesetconfiguration file for several operators.

 I used the quay-operator with version `3.8.8` in channel `stable-3.8` as an example to reproduce this issue.

```console
# oc mirror --config=./imagesetconfiguration.yaml file://.
Creating directory: oc-mirror-workspace/src/publish
Creating directory: oc-mirror-workspace/src/v2
Creating directory: oc-mirror-workspace/src/charts
Creating directory: oc-mirror-workspace/src/release-signatures
No metadata detected, creating new workspace
The current default channel was not valid, so an attempt was made to automatically assign a new default channel, which has failed.
The failure occurred because none of the remaining channels contain a "olm.channel" priority property, so it was not possible to establish a channel to use as the default channel.

This can be resolved by one of the following changes:
1) assign a "olm.channel" property on the appropriate channels to establish a channel priority
2) modify the default channel manually in the catalog
3) by changing the ImageSetConfiguration to filter channels or packages in such as way that it will include a package version that exists in the current default channel

The rendered catalog is invalid.

Run "oc-mirror list operators --catalog CATALOG-NAME --package PACKAGE-NAME" for more information.

error: error generating diff: the current default channel "stable-3.9" for package "quay-operator" could not be determined... ensure that your ImageSetConfiguration filtering criteria results in a package version that exists in the current default channel
```

As this is our main use case for the `oc mirror` tool, I would appreciate suggestions for different tools/solutions for this problem.

# What did you expect to happen?

Ablility to mirror the operator without including the current default channel `stable-3.9`.

# How to reproduce it (as minimally and precisely as possible)?

```console
# cat imagesetconfiguration.yaml
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: .
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.12
    packages:
    - name: quay-operator
      channels:
      - name: stable-3.8
        minVersion: '3.8.8'
        maxVersion: '3.8.8'

# oc mirror --config=./imagesetconfiguration.yaml file://.
```

Please let me know, if you need further information.

# References

Similar, but closed issue: #538. 
[This example](https://github.com/openshift/oc-mirror/blob/f3a42beed4aa77cced1a0624a6fce7af98f50011/docs/examples/imageset-config-catalog-include-default.yaml) points out the existing issue.

**Comment by dadav** [comment]
Especially annoying when the default changes :(

**Comment by BadgerOps** [comment]
Looks like a PR just got opened up [here](https://github.com/openshift/oc-mirror/pull/749) to address this issue! :tada:

**Comment by Skalador** [comment]
Thanks for the great news! I will close the issue as soon as the PR is merged.
