### ISSUE TITLE
ability to install via: go install 

### ISSUE THREAD

**Issue by garethahealy** [openshift/oc-mirror#79]
I think `go install` is a pretty well-known/standard approach. but currently, if I do that I get:

```
$ go install github.com/RedHatGov/bundle@latest
go: downloading github.com/RedHatGov/bundle v0.1.0-alpha.1
go install github.com/RedHatGov/bundle@latest: module github.com/RedHatGov/bundle@latest found (v0.1.0-alpha.1), but does not contain package github.com/RedHatGov/bundle
```

**Comment by afflom** [comment]
Thanks for the heads up. We have a few options to fix this, so we'll eval our options and let you know.

**Comment by jpower432** [comment]
@garethahealy We have to use replace directives in our go.mod due to our use of `oc` libraries and I believe this restricted with `go install`.

**Comment by afflom** [comment]
```
⬢[a@toolbox ~]$ go install github.com/containers/podman@latest
go: downloading github.com/containers/podman v1.9.3
go install github.com/containers/podman@latest: module github.com/containers/podman@latest found (v1.9.3), but does not contain package github.com/containers/podman
```
Same behavior with podman

**Comment by afflom** [comment]
To clarify: not because we don't want to. Just because replace is not supported by go install (from our understanding).
