### ISSUE TITLE
How can community members best engage with Red Hat Product/Engineering in this repo?

### ISSUE THREAD

**Issue by BadgerOps** [openshift/oc-mirror#809]
Hello all,

I am trying to figure out the best place to have a conversation with Red Hat teams on oc-mirror. 

The support case route tends to not be a good place for longer-form conversations, as that mechanism is optimized for resolve & close customer reported problems.

I recognize the complexity of supporting multiple versions of Open Shift, oc-mirror, etc across multiple enclave types; along with the balance between developing in-the-open and internal Red Hat discussions.

All that said, I, along with other oc-mirror users, need a good mechanism to have a conversation with the oc-mirror development team with regards to issues uncovered with using oc-mirror to replicate Platform, Operator and Container images to offline/disconnected instances.

If there is a better mechanism than Github issues, can we get the README.md or https://github.com/openshift/oc-mirror/blob/main/CONTRIBUTING.md updated with the best way to engage?

I sincerely desire to help improve oc-mirror, but at this point feel like there is no way to adequately communicate with the team.

Thank you,

-Sol

**Comment by lmzuccarelli** [comment]
@BadgerOps - Thanks for raising this point.  We have an internal RedHat slack channel, not sure if you are outside RedHat that you would be able to access it (#forum-oc-mirror fyi).

I think for now lets use GitHub issues,  we can exchange emails etc and work out a way to communicate if thats ok ?

**Comment by BadgerOps** [comment]
Hi @lmzuccarelli  thank you for the response.

I believe that GitHub issues is a good path forward, from an open conversation standpoint - which hopefully will benefit the entire community using the openshift tools, specifically oc-mirror.

While I recognize, and empathize with the difficulty of juggling multiple areas of communication, I believe it would be very helpful for some of the Red Hat product and technical leadership to be actively involved in discussions raised in the GitHub repos. There are obviously already some good examples of this happening, but it doesn't seem consistently a priority. 
As someone who's been on that side of the conversation multiple times, I want to emphasize that I understand - but truely believe that better engagement on this platform is necessary.

Again, thank you for the response and I look forward to collaborating with you and the team as we utilize oc-mirror and the surrounding tooling in our environment.

Thank you,

-Sol

**Comment by BadgerOps** [comment]
edit: I re-wrote the title, I don't want it to sound adversarial, but rather looking for collaboration.
