### ISSUE TITLE
Download latest upgrade graph image

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#94]
Download latest cincinnati graph data image when mirror:ocp:graph is true in the imageset-config and generate the require `Cincinnati` manifest

**Comment by jpower432** [comment]
@afflom Where is graph data coming from?

**Comment by afflom** [comment]
I think that should be assembled from the API that we pull Cincinnati from now

**Comment by jpower432** [comment]
Seems like there is a template for construction here -> https://github.com/openshift/cincinnati-graph-data/blob/master/Dockerfile

**Comment by jpower432** [comment]
One consideration here that is referenced in the enhancement for this is we sign the generated image and give the user a mechanism for verification. This is something we could provide for the FBC image as well. Thoughts @afflom?

**Comment by afflom** [comment]
> One consideration here that is referenced in the enhancement for this is we sign the generated image and give the user a mechanism for verification. This is something we could provide for the FBC image as well. Thoughts @afflom?

I suggest an iterative approach to this:
1. get the cincinnati image published along with the fbc
2. in an upcoming release, start signing with a self signed cert
3. beyond that, allow a user to reference a GPG key for custom signing.
